### ISSUE TITLE
Include `err` in callback

### ISSUE THREAD

**Issue by rvagg** [juliangruber/count-stream#1]
I'd love if I could get a standard callback from this with `err` argument and data second.

This is how I'm doing it in bl (and how I think @maxogden should do it in concat-stream too): https://github.com/rvagg/bl/blob/master/bl.js#L14-L26

I can send a PR if you're happy with the change?

**Comment by juliangruber** [comment]
I think it should either be

``` js
source
.on('error', function(err){
  // ...
})
.pipe(count(function(c){
  // ...
}));
```

or

``` js
count(source, function(err, c){
  // ...
});
```

but

``` js
source
.pipe(count(err, c){
  // ...
});
```

mixes patterns and makes it even worse.

**Comment by rvagg** [comment]
okay dokay
